### ISSUE TITLE
短編が文字化けします

### ISSUE THREAD

**Issue by mochacat2001** [kazuto28/syosetu-dl#1]
短編の小説をダウンロードすると文字化けします。

**Comment by Keinsleif** [comment]
実行環境の記載がなかったため、Windows環境だと勝手に判断しました

Issueを受けて、文字化けについては ver 1.6.2 で修正しました。
アップデートを行い、確認してください

Windowsは正式にはサポートしていませんので、使用の際はお気を付けください
